export const menuData = [
  {
    id: "Breakfast",
    title: "Breakfast",
    items: [
      {
        id: "Dabo Firfir",
        name: "Dabo Firfir",
        description: "Dabo Firfir - Spicy Ethiopian bread tossed in a rich, flavorful berbere sauce. A hearty and satisfying breakfast!",
        price: 15.99,
        image: "/images/Dabo-firfir.png",
        dietary: ["Vegetarian option"],
      },
      {
        id: "inkulal firfir",
        name: "Inkulal Firfir",
        description: "Hearty mashed fava beans cooked with spices, topped with fresh tomatoes, onions, and chili, served with bread or injera. Flavorful and filling!",
        price: 15.99,
        image: "/images/Enkulal-firfir.png",
        dietary: ["Vegetarian"],
      },
      {
        id: "Foul Special",
        name: "Foul Special",
        description: "Heart mashed fava beans cooked with spices,topped with fresh tomatoes, onions, and chili, served with bread or injera. Flavorful and filling!",
        price: 19.99,
        image: "/images/Foul-Fasting.png",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "Foul Fasting",
        name: "Foul Fasting",
        description: "Mashed fava beans cooked with spices, served with fresh tomatoes, onions, and chili, perfect for a hearty and vegan-friendly meal!",
        price: 19.99,
        image: "/images/Foul-Fasting.png",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "Kita Firfir",
        name: "Kita Firfir",
        description: "shredded Ethiopian flatbread mixed with spiced butter and berbere sauce, creating a warm, flavorful, and comforting breakfast dish.",
        price: 6.99,
        image: "/images/Kita-firfir.png",
        dietary: ["Vegetarian"],
      },
    ],
  },
  {
    id: "Fish",
    title: "Fish",
    items: [
      {
        id: "fish Cotelet ",
        name: "Doro Wat",
        description: "Crispy, golden-brown fish cutlets seasoned with aromatic spices,served with a side of dipping sauce for a deliciously satifying bite.",
        price: 19.99,
        image: "/images/Fish-Cotelet.png",
      },
      {
        id: "Fish Gulashe",
        name: "Fish Gulashe",
        description: "Tender fish simmered in a rich, spiced tomato sauce, served with bread or injera for a hearty and flavorful dish.",
        price: 19.99,
        image: "/images/Fish-gulashe.png",
      },
      {
        id: "Fish Dulet",
        name: "Fish Dulet",
        description: "Finedly chopped fish sauteed with anions,garlic, and Ethiopian spices, creating a bold and flavorful dish served with injera and bread.",
        price: 19.99,
        image: "/images/Fish-Dulet.png",
      },
      // {
      //   id: "shiro",
      //   name: "Shiro",
      //   description: "Spiced and ground chickpea stew, slow-cooked to perfection.",
      //   price: 15.99,
      //   image: "/images/shiro.jpg",
      //   dietary: ["Vegetarian"],
      // },
      // {
      //   id: "gored-gored",
      //   name: "Kikil",
      //   description: "Tender beef cubes cooked in a spicy sauce with Ethiopian spices.",
      //   price: 20.99,
      //   image: "/images/qiqil.jpg",
      // }
    ],
  },
  {
    id: "vegetarian",
    title: "Vegetarian Options",
    items: [
      {
        id: "Firfir",
        name: "Firfir",
        description: "Shredded injera mixed with a spicy berbere sauce, onion, and clarified butter, creating a tangy amd flavorful Ethiopian dish.",
        price: 16.00,
        image: "/images/firfir.png",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "Shiro",
        name: "Shiro",
        description: "A single crispy, golden triangle of delight, our signature samosa encases a hearty filling of spiced potatoes, peas, and a hint of fresh herbs.",
        price: 17.00,
        image: "/images/shiro.png",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "Pasta Fasting",
        name: "Pasta Fasting",
        description: "Light and flavorful pasta dish prepared with fresh tomatoes, garlic, and herbs, perfect for those observing fasting or seeking a vegan option.",
        price: 19.00,
        image: "/images/pastaFasting.png",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "Vegie Combo",
        name: "Vegie Combo",
        description: "A delightful assortment of various vegetarian Ethiopian dishes, including lentils, chickpeas, greens, and vegetables, all seasoned with injera. This combo offers a diverse and flavorful experience for those who enjoys a variety of tastes and textures in one meal,",
        price: 25.00,
        image: "/images/Vegie-combo.png",
        dietary: ["Vegetarian"],
      },
    ],
  },
  {
    id: "Main Course",
    title: "Main Course",
    items: [
      {
        id: "Kitfo",
        name: "Kitfo",
        description: "Delicious minced raw beef, blended with traditional Ethiopian spices and clarified butter, accompanied by injera, fresh cottage cheese, and sauteed greens.",
        price: 19.00,
        image: "/images/Kitfo.png",
      },
      {
        id: "Firfir Sega",
        name: "Firfir Sega",
        description: "Slow-cooked tender meat simmered in a rich, spicy sauce infused with Ethiopian berebere, onion, and garlic. Served with injera for a bold and hearty flavor experience.",
        price: 19.00,
        image: "/images/Firfir-sega.png",
      },
      {
        id: "Past with Beef",
        name: "Past with Beef",
        description: "Flavorful pasta combined with tender beef, fresh tomatoes, garlic,a nd aromatic herbs, delivering a hearty and conforting dish.",
        price: 19.00,
        image: "/images/Pasta-with-Beef.png",
        dietary: ["Vegan"],
      },
      {
        id: "Awaze Tibse (Lambo)",
        name: "Awaze Tibse (Lambo)",
        description: "Tender lamb pieces sauteed with Ethiopian spices and a zenty awaze sauce,paired with injera for a bold and flavorful treat.",
        price: 20.00,
        image: "/images/Awaze-tibse_lamp.png",
        dietary: ["Vegan"],
      },
      {
        id: "Awaze Tibse (Beef)",
        name: "Awaze Tibse (Beef)",
        description: "Juicy beef sauteed with Ethiopian spices and a vibrant award sauce, served with injera for a rich and satisfying flavor experience.",
        price: 20.00,
        image: "/images/Awaze-tibse_lamp.png",
      },
      {
        id: "Dereke Tibse",
        name: "Dereke Tibse",
        description: "Succulent lamb sauteed with authentic Ethiopian spices and a bold awaze sauce, served alongside injera for a flavorful and spicy delight.",
        price: 20.00,
        image: "/images/Derek-Tibse.png",
      },
      // {
      //   id: "Ferefer Be Siga(Beef)",
      //   name: "Dereke Tibse",
      //   description: "Succulent lamb sauteed with authentic Ethiopian spices and a bold awaze sauce, served alongside injera for a flavorful and spicy delight.",
      //   price: 17.00,
      //   image: "/images/Firfir-besiga.png",
      // },
      {
        id: "Gaslight Tibse",
        name: "Gaslight Tibse",
        description: "Sizzling beef strips marinated in a medley of Ethiopian spices, sauteed with onions, tomatoes, and green peppers. This aromatic and spicy dish is served hot, delivering an authentic and unforgettable taste of Ethiopian cuisine.",
        price: 21.00,
        image: "/images/Gaslignt-Tibse.png",
      },
      {
        id: "Geba Weta",
        name: "Geba Weta",
        description: "A savory dish featuring tender beef cuts simmered in rich, spicy sauce infuced with traditional Ethiopian spices. Served with injera, it offers a hearty and authentic Ethiopian dining experience.",
        price: 19.00,
        image: "/images/Geba-weta.png",
      },
      {
        id: "Doro Wete",
        name: "Doro Wete",
        description: "A rich and spicy Ethiopian chicken stew slow-cooked with berbere, onion, and seasoned butter, served with injera for a deep, flavorful experience.",
        price: 24.99,
        image: "/images/doro-wet.png",
      },
      {
        id: "Gomen with Beef",
        name: "Gomen with Beef",
        description: "Tender beef cooked with collard greens, garlic, and spices, creating a hearty and flavorful Ethiopian dish served with injera!.",
        price: 19.99,
        image: "/images/Gomen-with-beef.png",
      },
    ],
  },
]
