export const menuData = [
  {
    id: "starters",
    title: "Starters",
    items: [
      {
        id: "sambusa",
        name: "Sambusa",
        description: "Crispy pastry filled with lentils or beef, seasoned with herbs and spices.",
        price: 6.99,
        image: "/images/sambusa.jpg",
        dietary: ["Vegetarian option"],
      },
      {
        id: "kategna",
        name: "Kategna",
        description: "Toasted injera with berbere and Ethiopian spiced butter.",
        price: 5.99,
        image: "/images/injera.jpg",
        dietary: ["Vegetarian"],
      },
      {
        id: "azifa",
        name: "Azifa",
        description: "Lentil salad with Ethiopian mustard, onions, jalapeño, and lemon juice.",
        price: 7.99,
        image: "/images/lentils.jpg",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "fitfit",
        name: "Fitfit",
        description: "Torn pieces of injera mixed with berbere sauce and various spices.",
        price: 6.99,
        image: "/images/spices.jpg",
        dietary: ["Vegetarian"],
      },
    ],
  },
  {
    id: "signature-dishes",
    title: "Signature Dishes",
    items: [
      {
        id: "doro-wat",
        name: "Doro Wat",
        description: "Spicy chicken stew with berbere sauce, served with a hard-boiled egg and injera.",
        price: 18.99,
        image: "/images/doro-wat.jpg",
      },
      {
        id: "kitfo",
        name: "Kitfo",
        description: "Minced raw beef seasoned with mitmita and niter kibbeh, served with ayib cheese and injera.",
        price: 19.99,
        image: "/images/kitfo.jpg",
      },
      {
        id: "tibs",
        name: "Special Tibs",
        description: "Sautéed beef or lamb with rosemary, onions, peppers, and Ethiopian spices.",
        price: 17.99,
        image: "/images/tibs.jpg",
      },
      {
        id: "shiro",
        name: "Shiro",
        description: "Spiced and ground chickpea stew, slow-cooked to perfection.",
        price: 15.99,
        image: "/images/shiro.jpg",
        dietary: ["Vegetarian"],
      },
    ],
  },
  {
    id: "vegetarian",
    title: "Vegetarian Specialties",
    items: [
      {
        id: "misir-wat",
        name: "Misir Wat",
        description: "Spicy red lentil stew cooked with berbere sauce and Ethiopian spices.",
        price: 14.99,
        image: "/images/lentils.jpg",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "gomen",
        name: "Gomen",
        description: "Collard greens sautéed with garlic, ginger, and spices.",
        price: 13.99,
        image: "/images/vegetables.jpg",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "atkilt-wat",
        name: "Atkilt Wat",
        description: "Cabbage, carrots, and potatoes simmered with turmeric and other spices.",
        price: 13.99,
        image: "/images/vegetables.jpg",
        dietary: ["Vegan", "Gluten-free"],
      },
      {
        id: "veggie-combo",
        name: "Vegetarian Combo",
        description: "A sampling of four vegetarian dishes served with injera.",
        price: 19.99,
        image: "/images/vegetables.jpg",
        dietary: ["Vegetarian"],
      },
    ],
  },
  {
    id: "beverages",
    title: "Beverages",
    items: [
      {
        id: "ethiopian-coffee",
        name: "Ethiopian Coffee Ceremony",
        description: "Traditional coffee service with freshly roasted beans (serves 2-4).",
        price: 12.99,
        image: "/images/coffee.jpg",
      },
      {
        id: "tej",
        name: "Tej",
        description: "Ethiopian honey wine with a sweet and distinctive flavor.",
        price: 8.99,
        image: "/images/coffee.jpg",
      },
      {
        id: "spris",
        name: "Spris",
        description: "Layered fruit juice drink with avocado, mango, and strawberry.",
        price: 6.99,
        image: "/images/coffee.jpg",
        dietary: ["Vegan"],
      },
      {
        id: "ethiopian-tea",
        name: "Ethiopian Spiced Tea",
        description: "Black tea infused with cardamom, cinnamon, and cloves.",
        price: 4.99,
        image: "/images/coffee.jpg",
        dietary: ["Vegan"],
      },
    ],
  },
]
